### ISSUE TITLE
Can't download human36m dataset

### ISSUE THREAD

**Issue by zhou07** [Lotayou/densebody_pytorch#18]
I can't download human36m dataset by the link provided in https://github.com/MandyMo/pytorch_HMR .  So can you provide the link?

**Comment by Lotayou** [comment]
Sorry pal, this dataset is licensed and only free for academic uses only, please check out the license agrrement [here](http://vision.imar.ro/human3.6m/eula.php). You have to turn to other people for help I'm afraid:)
