### ISSUE TITLE
I don't know how to use human3.6 dataset

### ISSUE THREAD

**Issue by zhou07** [Lotayou/densebody_pytorch#28]
Hi Lotayou,

Thanks for your work.
I'm following your steps to prepare my human3.6m data, but I can't find the annotation which are called  center, gt2d, gt3d, height, imagename, pose, shape, smpl_joint, width, so which part I need to download from offical website of human3.6m dataset?
![1](https://user-images.githubusercontent.com/32354174/58856157-7a075380-86d4-11e9-9f82-01a0832901ab.png)

**Comment by Lotayou** [comment]
Actually I'm using an unofficial dataset with pre-processed annotations. If you are interested in reproducing my experiments, leave me your email and I'll see what I can do.

**Comment by zhou07** [comment]
I am very interested in your work， and think this job is great and cool, so I want to reproduce the job. My email address is zlzhou77@gmail.com. Can you share the preprocessed dataset by other means such as BT seed?


------------------ 原始邮件 ------------------
发件人: "hello-world-zsp"<notifications@github.com>;
发送时间: 2019年6月5日(星期三) 晚上10:08
收件人: "Lotayou/densebody_pytorch"<densebody_pytorch@noreply.github.com>;
抄送: "周蕾"<1586674111@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Lotayou/densebody_pytorch] I don't know how to use human3.6dataset (#28)




Actually I'm using an unofficial dataset with pre-processed annotations. If you are interested in reproducing my experiments, leave me your email and I'll see what I can do.

**Comment by zhou07** [comment]
I am very interested in your work， and think this job is great and cool, so I want to reproduce the job. My email address is zlzhou77@gmail.com.

**Comment by zhou07** [comment]
I am very interested in your work， and think this job is great and cool, so I want to reproduce the job. My email address is zlzhou77@gmail.com.

**Comment by Lotayou** [comment]
Check your email these days. This post will be erased soon.

**Comment by zhou07** [comment]
Ok. Thank you very much.
