### ISSUE TITLE
what data do I need to download in Human3.6M?

### ISSUE THREAD

**Issue by lxy5513** [Lotayou/densebody_pytorch#36]
@Lotayou 
Thanks for your awesome work, I want train the human3.6M dataset, but I don't know what data do I need to download. Does the code need videos, pose, segments ? or I need download them all. Hope you can help me, thanks in advace. 

![image](https://user-images.githubusercontent.com/39720528/60316409-f1ab6400-999c-11e9-8d31-6260d13c9e9b.png)

**Comment by Lotayou** [comment]
Check the link in preps.md carefully...

**Comment by mathpopo** [comment]
> @Lotayou
> Thanks for your awesome work, I want train the human3.6M dataset, but I don't know what data do I need to download. Does the code need videos, pose, segments ? or I need download them all. Hope you can help me, thanks in advace.
> 
> ![image](https://user-images.githubusercontent.com/39720528/60316409-f1ab6400-999c-11e9-8d31-6260d13c9e9b.png)

hi ,could you share the dataset?

**Comment by Lotayou** [comment]
You need the original video and pose segmentation data, In addition you also need the mocap fitted SMPL mesh parameters in 24*3 format... I personally get the data from somewhere else (which has now expired), so you are on your own:P Thanks.
