### ISSUE TITLE
Could you attach your tested results and release pretrained model?

### ISSUE THREAD

**Issue by Maqingyang** [Lotayou/densebody_pytorch#37]
You really did an exllent work! It helps me a lot.
However, I met some problems when reproducing the results and I don't know what score you have achived using this code.So, I really expect that you can attach the tested scores and release pretrained model.

**Comment by Lotayou** [comment]
I didn't really tested the MPJPE score, but I did visulize the result for some images in testing dataset. Including the one showcased on README. If you need to compute scores  it's better to write your own script for this purpose. Send me an email if you want to discuss more about the problems you've encountered.
