### ISSUE TITLE
no model.pkl

### ISSUE THREAD

**Issue by LH-Abner** [Lotayou/densebody_pytorch#38]
Hello, I can not find the model.pkl  when I run the smpl_torch_batch.py. Could you tell me how to find it ?
Besides, there is  an 'indexerror: index 6890 is out of bounds for axis 0 with size 6890' when I run the triangulation.py, I do not know if the error is caused by the model.pkl, maybe there are some other mistakes? I put the 'for (i,line) in enumerate(lines):' modify to 'for (i,line) in enumerate(lines[0:6890]):', the indexerror is lost.But there is another 'indexerror:index 13790 is out of bounds for axis 0 with size 13776.

**Comment by Lotayou** [comment]
You must be using a wrong smpl_fbx file, make sure you download the .fbx  file from the official website, open it up with Blender software, and save as .obj format. The `model.pkl` is converted from the one on SMPL official website, make sure you register an account and download all necessary files first.

**Comment by plmsmile** [comment]
> You must be using a wrong smpl_fbx file, make sure you download the .fbx file from the official website, open it up with Blender software, and save as .obj format. The `model.pkl` is converted from the one on SMPL official website, make sure you register an account and download all necessary files first.

There are many fbx files in the official site. I have tried `mosh_cmu_0511_f_lbs_10_207_0_v1.0.2.fbx`
, `basicModel_f_lbs_10_207_0_v1.0.2.fbx`. However, the index 6890 out of bounds bug is still there. 
So which fbx file should be used, and could you share the  converted .obj file? Thank you a lot~
