### ISSUE TITLE
The shape of output .obj and .pkl is wrong 

### ISSUE THREAD

**Issue by UnrealPawn** [Lotayou/densebody_pytorch#48]
Hi Lotayou,
Thank you for your work and detailed instructions. 
I followed your steps to prepare Datasets and UV.
![image](https://user-images.githubusercontent.com/18569643/64935807-89329b80-d896-11e9-822f-55122dde7bad.png)

However I got wrong results on the model I trained by myself 
and I also tested on your pre-trained model.
![image](https://user-images.githubusercontent.com/18569643/64935530-2987c080-d895-11e9-91de-1f7c01f93e71.png)

Maybe My SMPL model isn't right?
And I have no ideal which step I failed. Any help would be deeply appreciated! ^_^

**Comment by UnrealPawn** [comment]
@Lotayou can you give me some advise?

**Comment by Lotayou** [comment]
How many vertices and faces are there in your .obj file?
The pre-trained model isn't perfect, you may need to fine-tune it on your data, provided you have the matching annotations, that is. But anyway, I'll look into it when I have the time.

**Comment by UnrealPawn** [comment]
@Lotayou Thank you very much for your timely response :D 
there are 6890 vertices and 13776 faces 
![image](https://user-images.githubusercontent.com/18569643/64938808-69a17000-d8a2-11e9-9222-cd005507049c.png)
And the smpl_fbx_template.obj looks fine, but all output .obj looks strange, should I try to make my own model_lsp.pk?
![image](https://user-images.githubusercontent.com/18569643/64938811-6dcd8d80-d8a2-11e9-8a15-432543edb625.png)

**Comment by UnrealPawn** [comment]
And I try to use UV map generated by (create_UV_maps.py) to reconstructe SMPL model. The shape like this :
![image](https://user-images.githubusercontent.com/18569643/64940383-2c8bac80-d8a7-11e9-922f-fba6699ee5da.png)
