### ISSUE TITLE
Issues with UV Map Generation and Subsequent SMPL Object Generation

### ISSUE THREAD

**Issue by yongyct** [Lotayou/densebody_pytorch#49]
Hi,

I am trying out this repo, and am trying to generate a 3D SMPL model out of a 2D image using the "in-the-wild" mode.

I used the sample image found in the teaser folder, and the UV Maps & SMPL Model generated appears cranky.

![densebody_resnet200_00000](https://user-images.githubusercontent.com/53852395/66255928-b4d0e380-e7bb-11e9-8c7a-71c7946e9ebf.png)

![image](https://user-images.githubusercontent.com/53852395/66255946-ca460d80-e7bb-11e9-866e-dfafccf2aef1.png)

Not sure if I am doing something wrong...
Using the below parameters:
- Using the [encoder](https://yadi.sk/d/isvVFGIU6cHueQ) & [decoder](https://yadi.sk/d/ck-JBue4XYNpHQ) weights
- Using `model_lsp.pkl` generated via instructions [here](https://github.com/Lotayou/densebody_pytorch/issues/22#issuecomment-487764430)
- Using `radvani.pickle` generated from [template.obj](https://github.com/Lotayou/densebody_pytorch/issues/4#issuecomment-481480724) via `UV_Map_Generator` class, and the resulting `barycentric_h0256_w0256_radvani.pickle`
- Saw this [issue](https://github.com/Lotayou/densebody_pytorch/issues/41) and tried using [-1, 1] (by default via `densebody_dataset.py`) & [0, 255] UV Maps output, but both gave similar results above

**Comment by Lotayou** [comment]
It's weird to have such a distorted mesh. Can you try to create a UV position map from the template model, and use the `resample` method from `UV_Map_Generator` class to see if you can recover the regular T-pose?

**Comment by yongyct** [comment]
I think 1 issue was that the encoder/decoder weights that were provided were trained with the SMPL UV Map, hence there was a need to use [smpl template object](https://github.com/Lotayou/densebody_pytorch/issues/4#issuecomment-479301776) instead of [radvani template object](https://github.com/Lotayou/densebody_pytorch/issues/4#issuecomment-481480724).

I changed to using the smpl template object, and at least I see some slight resemblance now (though the mesh still looks distorted after trying both [-1, 1] & [0, 255] uv map outputs):
*Sample 1*
![image](https://user-images.githubusercontent.com/53852395/66623614-0d223e00-ec1f-11e9-955a-66c204ba7e87.png)
![image](https://user-images.githubusercontent.com/53852395/66623642-30e58400-ec1f-11e9-9091-c96209074674.png)
*Sample 2*
![image](https://user-images.githubusercontent.com/53852395/66623703-77d37980-ec1f-11e9-8ab6-b329d2f05a1e.png)
![image](https://user-images.githubusercontent.com/53852395/66623698-730ec580-ec1f-11e9-8584-fbb0672fddb0.png)

Let me try to regenerate UV Map based on [this](https://github.com/Lotayou/densebody_pytorch/blob/master/UV_MAPS.md)

**Comment by Lotayou** [comment]
It clearly makes more sense now. Although I found this network performs badly when dealing with images in-the-wild. In other words, the network fails to generalize to other images beyond human 36M. I think maybe incorporating a segmentation network would help resolve the issue.

**Comment by yongyct** [comment]
Thanks a lot @Lotayou! I think I will close the issue now since the issue is more of an enhancement rather than a bug.
