### ISSUE TITLE
body measurements

### ISSUE THREAD

**Issue by Piero-M** [Lotayou/densebody_pytorch#50]
congratulations on your work, is it possible to extract measurements from the mesh file?

**Comment by Lotayou** [comment]
Yes it is possible, once you acquired the estimated UV map you can resample it back to a human mesh using `UV_Map_Generator::resample` function, then if you want to acquire the normal skeleton representation just multiply the [6890, 3] vertex matrix with the `joint_regressor` matrix stored in the official SMPL model.

**Comment by Piero-M** [comment]
what would be the accuracy of the model?

**Comment by Lotayou** [comment]
depend on your task. If it's for 3D pose estimation, just align the estimated joints with ground truth and report MPJPE
