### ISSUE TITLE
how to configure pretrained model?

### ISSUE THREAD

**Issue by electronicliujiang** [Lotayou/densebody_pytorch#51]

**Comment by electronicliujiang** [comment]
where is radvani_template.pickle  and model_lsp.pkl?
Can model_lsp.pkl be replaced by SMPLX_MALE.pkl?

**Comment by Lotayou** [comment]
Basically you need a SMPL model with additional pretrained-weights on Microsoft COCO dataset for 19-point skeleton inference from SMPL models. It should be a [6890*19] tensor. You can start by looking at [End-to-end Recovery of Human Shape and Pose](https://github.com/akanazawa/hmr)

For radvani_template.pickle, download provided .obj model from [FAQ page](https://github.com/Lotayou/densebody_pytorch/issues/4) and follow the instructions in `PREP.md`
