### ISSUE TITLE
The scale of  x,y,z  in UV map is  different

### ISSUE THREAD

**Issue by 2294462474** [Lotayou/densebody_pytorch#53]
_min = np.amin(verts, axis=0, keepdims=True)
        _max = np.amax(verts, axis=0, keepdims=True)
        verts = (verts - _min) / (_max - _min)``
![image](https://user-images.githubusercontent.com/25993171/69333811-648ee180-0c94-11ea-9298-65311c84079f.png)

I think here is wrong, the scale of x,y,z  is different

**Comment by Lotayou** [comment]
Great observation. I've not managed to solve this problem yet, since humans possess varying body shapes and builds, but should all be normalized to [0,1] for UV coordinate conversion in order to fuly utilize the RGB range. Think you have a better solution for this? Feel free to submit a PR:)
