### ISSUE TITLE
Any solutions for extracting texture from the image and fitting to this model.

### ISSUE THREAD

**Issue by AIdeveloper-oz** [Lotayou/densebody_pytorch#56]
Hi, Thanks for sharing this amazing work. This will  strongly support my research. I need to develop a 3d model with the scanned image. This project has the first part of developing the skeleton. How can I add texture of the same image to this?

**Comment by Lotayou** [comment]
[MPI's work](https://www.researchgate.net/publication/335290763_360-Degree_Textures_of_People_in_Clothing_from_a_Single_Image)
