### ISSUE TITLE
How is the annotation_large.h5 generated from human 3.6M in data_washing.py?

### ISSUE THREAD

**Issue by fliman** [Lotayou/densebody_pytorch#57]
when I ran data_washing.py, it reported missing annotation_large.h5. How is this file generated? I use  https://github.com/anibali/h36m-fetch to preprocess human3.6m it only generated anno.h5 file for each subject.

**Comment by Lotayou** [comment]
Well I haven't any clue either :P. This annotation file comes from another project which is now expired.

**Comment by 2a3b4c** [comment]
> Well I haven't any clue either :P. This annotation file comes from another project which is now expired.

can you provide the link or paper about this expired project, thanks
